### ISSUE TITLE
Bot attempts to parse images as strings

### ISSUE THREAD

**Issue by LevBernstein** [LevBernstein/LevQuizbowlBot#3]
The bot examines every message to see if it's a command, including messages that are just people sending images. The bot tries to read the image like a string, which creates issues with the isInt() helper  method. Full output here:

Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/discord/client.py", line 333, in _run_event
    await coro(*args, **kwargs)
  File "QBBot.py", line 371, in on_message
    if len(games) != 0 and isInt(text.content): # Assigns points. Checks len games to avoid unnecessary calls.
  File "QBBot.py", line 30, in isInt
    if st[0] == '-' or st[0] == '+':
IndexError: string index out of range

**Comment by LevBernstein** [comment]
Resolved with latest commit.
